language: python
services:
  - redis-server
python:
  - "3.6"
  - "3.7-dev" # 3.7 development branch
install:
  - pip install -r requirements.txt
script:
  - nosetests  -v --with-coverage --cover-branches --cover-erase --cover-package tornado_stale_client tests/

